trigger: 
- main

pool: Unreal

resources:
  repositories:
    - repository: devops
      type: git
      name: plugins-unreal-publishing
      
variables: 
- template: template-variables.yml@devops

extends:
  template: template-github.yml@devops
